---
version: '2'

services:
# Traefik
  traefik:
    image: traefik
    ports:
        - "80:80"
        - "443:443"
        - "8080:8080"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./traefik/traefik.toml:/traefik.toml
        - ./traefik/acme.json:/acme.json
# Geoip API nodejs app
  nodejs-app:
    build:
        context: ./njs-traefik-docker
    volumes:
        - ./api-provider:/app
    labels:
        - "traefik.backend=nodejs-app"
        - "traefik.frontend.rule=Host:api.flavien-hardy.me"
        - "traefik.port=3000"
    depends_on:
        - traefik
