---
version: '2'

volumes:
  vault:
    external: true
  consul:
    external: true
  registry-web-db:
    external: true

services:
# Traefik
  traefik:
    image: traefik
    restart: always
    ports:
        - "163.172.35.163:80:80"
        - "163.172.35.163:443:443"
        - "163.172.35.163:8080:8080"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./traefik/traefik.toml:/traefik.toml
        - ./traefik/acme-v2.json:/acme.json

# Geoip API nodejs app
  nodejs-app:
    build:
        context: ./njs-traefik-docker
    volumes:
        - ./api-provider:/app
    labels:
        - "traefik.backend=nodejs-app"
        - "traefik.frontend.rule=Host:api.flhar.ovh"
        - "traefik.port=3000"
    depends_on:
        - traefik

# Local registry
  registry:
    image: registry
    restart: always
    #environment:
    #    REGISTRY_AUTH: htpasswd
    #    REGISTRY_AUTH_HTPASSWD_PATH: /var/lib/registry/conf.d/htpasswd
    #    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
        - /var/lib/registry:/var/lib/registry
    labels:
        - "traefik.backend=registry"
        - "traefik.frontend.rule=Host:registry.flhar.ovh"
        - "traefik.port=5000"
    depends_on:
        - traefik

# Web registry viewer
  registry-web:
    image: hyper/docker-registry-web
    restart: always
    links:
        - registry
    environment:
        REGISTRY_URL: http://registry:5000/v2
    volumes:
        - registry-web-db:/data
        - ./registry-web/registry-web.yml:/conf/config.yml:ro
    labels:
        - "traefik.backend=registry-web"
        - "traefik.frontend.rule=Host:registry-web.flhar.ovh"
        - "traefik.port=8080"
    depends_on:
        - traefik
        - registry

# DNS
  bind:
    image: sameersbn/bind
    restart: always
    ports:
        - "127.0.0.1:53:53/tcp"
        - "127.0.0.1:53:53/udp"
    volumes:
        - ./bind/:/data/bind
    environment:
        - WEBMIN_ENABLED=False

# Apache directory listing
  share:
    image: php:apache
    restart: always
    volumes:
        - ./share:/var/www/html
    labels:
        - "traefik.backend=share"
        - "traefik.frontend.rule=Host:share.flhar.ovh"
        - "traefik.port=80"
    depends_on:
        - traefik

# Apache directory listing
  draw:
    image: httpd
    restart: always
    volumes:
        - ./draw.io/war/:/usr/local/apache2/htdocs/
    labels:
        - "traefik.backend=draw"
        - "traefik.frontend.rule=Host:draw.flhar.ovh"
        - "traefik.port=80"
    depends_on:
        - traefik

# Vault @Hashicorp
  vault:
    image: vault
    restart: always
    command: server
    volumes:
        - vault:/vault/file
        - ./vault/config:/vault/config
    labels:
        - "traefik.backend=fault"
        - "traefik.frontend.rule=Host:vault.flhar.ovh"
        - "traefik.port=8200"
    depends_on:
        - traefik

# Consul @Hashicorp
  consul:
    image: consul
    restart: always
    volumes:
        - consul:/consul/data
        - ./consul/config:/consul/config
    network_mode: host
