---
version: '2'

volumes:
  vault:
    external: true
  consul:
    external: true
  apt-cacher-ng:
    external: true
  asciinema:
    external: true
  mysql:
    external: true

services:
# Traefik
  traefik:
    image: traefik
    restart: always
    network_mode: host
    ports:
        - "163.172.35.163:80:80"
        - "163.172.35.163:443:443"
        - "163.172.35.163:8080:8080"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./traefik/traefik.toml:/traefik.toml
        - ./traefik/acme-v2.json:/acme.json

# Geoip API nodejs app
  nodejs-app:
    build:
        context: ./njs-traefik-docker
    volumes:
        - ./api-provider:/app
    labels:
        - "traefik.backend=nodejs-app"
        - "traefik.frontend.rule=Host:api.flhar.ovh"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.port=3000"
    depends_on:
        - traefik

# Local registry
  registry:
    image: registry
    restart: always
    #environment:
    #    REGISTRY_AUTH: htpasswd
    #    REGISTRY_AUTH_HTPASSWD_PATH: /var/lib/registry/conf.d/htpasswd
    #    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
        - /var/lib/registry:/var/lib/registry
    labels:
        - "traefik.backend=registry"
        - "traefik.frontend.rule=Host:registry.flhar.ovh"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.port=5000"
    depends_on:
        - traefik

# Web registry viewer
  registry-web:
    image: konradkleine/docker-registry-frontend:v2
    restart: always
    links:
        - registry
    environment:
        ENV_DOCKER_REGISTRY_HOST: registry
        ENV_DOCKER_REGISTRY_PORT: 5000
    #volumes:
    #    - registry-web-db:/data
    #    - ./registry-web/registry-web.yml:/conf/config.yml:ro
    labels:
        - "traefik.backend=registry-web"
        - "traefik.frontend.rule=Host:registry-web.flhar.ovh"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.port=80"
    depends_on:
        - traefik
        - registry

# DNS
  bind:
    image: sameersbn/bind
    restart: always
    ports:
        - "127.0.0.1:53:53/tcp"
        - "127.0.0.1:53:53/udp"
    volumes:
        - ./bind/:/data/bind
    environment:
        - WEBMIN_ENABLED=False

# Apache directory listing
  share:
    image: php:apache
    restart: always
    volumes:
        - ./share:/var/www/html
    labels:
        - "traefik.backend=share"
        - "traefik.frontend.rule=Host:share.flhar.ovh"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.port=80"
    depends_on:
        - traefik

# APT cacher ng
  apt-cacher-ng:
    image: sameersbn/apt-cacher-ng
    restart: always
    volumes:
        - apt-cacher-ng:/var/cache/apt-cacher-ng
    ports:
        - 10.91.132.82:3142:3142

# Draw.io
  draw:
    image: httpd
    restart: always
    volumes:
        - ./draw.io/war/:/usr/local/apache2/htdocs/
    labels:
        - "traefik.backend=draw"
        - "traefik.frontend.rule=Host:draw.flhar.ovh"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.port=80"
    depends_on:
        - traefik

# Vault @Hashicorp
  vault:
    image: vault
    restart: always
    command: server
    volumes:
        - vault:/vault/file
        - ./vault/config:/vault/config
    labels:
        - "traefik.backend=fault"
        - "traefik.frontend.rule=Host:vault.flhar.ovh"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.port=8200"
    depends_on:
        - traefik

# Consul @Hashicorp
  consul:
    image: consul
    restart: always
    volumes:
        - consul:/consul/data
        - ./consul/config:/consul/config
    network_mode: host

# Asciinema
  postgres:
    image: postgres
  redis:
    image: redis
  sidekiq:
    image: asciinema/asciinema.org
    links:
      - redis
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:mypass@postgres/asciinema"
      REDIS_URL: "redis://redis:6379"
      HOST: "asciinema.fhardy.fr"
    command: "ruby start_sidekiq.rb"
    volumes:
      - asciinema:/app/uploads
      - ./asciinema/asciinema.yml:/app/config/asciinema.yml
      - ./asciinema/production.rb:/app/config/environments/production.rb
  asciinema:
    image: asciinema/asciinema.org
    links:
      - redis
      - postgres
    depends_on:
      - sidekiq
    environment:
      DATABASE_URL: "postgresql://postgres:mypass@postgres/asciinema"
      REDIS_URL: "redis://redis:6379"
      HOST: "asciinema.fhardy.fr" # replace with actual hostname/ip.... ${HOSTNAME} doesn't seem to work..
    volumes:
      - asciinema:/app/uploads
      - ./asciinema/asciinema.yml:/app/config/asciinema.yml
    labels:
        - "traefik.backend=asciinema"
        - "traefik.frontend.rule=Host:asciinema.fhardy.fr"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.port=3000"

# Etherpad
  mysql:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "totolitoto"

  etherpad:
    image: tvelocity/etherpad-lite
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      ETHERPAD_DB_HOST: "mysql"
      ETHERPAD_DB_PASSWORD: "totolitoto"
    labels:
        - "traefik.backend=etherpad"
        - "traefik.frontend.rule=Host:pads.fhardy.fr"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.port=9001"
