---
version: '2'

volumes:
  vault:
    external: true
  consul:
    external: true

services:
# Traefik
  traefik:
    image: traefik
    restart: always
    ports:
        - "163.172.35.163:80:80"
        - "163.172.35.163:443:443"
        - "163.172.35.163:8080:8080"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./traefik/traefik.toml:/traefik.toml
        - ./traefik/acme.json:/acme.json

# Geoip API nodejs app
  nodejs-app:
    build:
        context: ./njs-traefik-docker
    volumes:
        - ./api-provider:/app
    labels:
        - "traefik.backend=nodejs-app"
        - "traefik.frontend.rule=Host:api.flavien-hardy.me"
        - "traefik.port=3000"
    depends_on:
        - traefik

# Local registry
  registry:
    image: registry
    restart: always
    #environment:
    #    REGISTRY_AUTH: htpasswd
    #    REGISTRY_AUTH_HTPASSWD_PATH: /var/lib/registry/conf.d/htpasswd
    #    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
        - /var/lib/registry:/var/lib/registry
    labels:
        - "traefik.backend=registry"
        - "traefik.frontend.rule=Host:registry.flavien-hardy.me"
        - "traefik.port=5000"
    depends_on:
        - traefik

# DNS
  bind:
    image: sameersbn/bind
    restart: always
    ports:
        - "127.0.0.1:53:53/tcp"
        - "127.0.0.1:53:53/udp"
    volumes:
        - ./bind/:/data/bind
    environment:
        - WEBMIN_ENABLED=False

# Apache directory listing
  share:
    image: php:apache
    restart: always
    volumes:
        - ./share:/var/www/html
    labels:
        - "traefik.backend=share"
        - "traefik.frontend.rule=Host:share.flavien-hardy.me"
        - "traefik.port=80"
    depends_on:
        - traefik

# Vault @Hashicorp
  vault:
    image: vault
    restart: always
    command: server
    volumes:
        - vault:/vault/file
        - ./vault/config:/vault/config
    labels:
        - "traefik.backend=fault"
        - "traefik.frontend.rule=Host:vault.flavien-hardy.me"
        - "traefik.port=8200"
    depends_on:
        - traefik

# Consul @Hashicorp
  consul:
    image: consul
    restart: always
    volumes:
        - consul:/consul/data
        - ./consul/config:/consul/config
    network_mode: host
