apiVersion: v1
kind: Namespace
metadata:
  name: drawio
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: drawio
  namespace: drawio
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    ingress.kubernetes.io/force-ssl-redirect: 'true'
spec:
  rules:
    - host: drawio.k8s.fhardy.fr
      http:
        paths:
          - backend:
              serviceName: drawio
              servicePort: 80
            path: /
  tls:
    - hosts:
        - drawio.k8s.fhardy.fr
      secretName: drawio-tls
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: drawio
  name: drawio
  namespace: drawio
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: drawio
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: drawio
  name: drawio
  namespace: drawio
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: drawio
    spec:
      containers:
      - name: drawio
        image: fhardy/draw.io:latest
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 30
