---
version: '3.1'

networks:
  registry:
    external: true

volumes:
  registry:
    driver: nfs
    driver_opts:
      share: "10.20.30.2:/registry"

services:
  registry:
    image: registry
    networks:
      - registry
#    environment:
#      REGISTRY_AUTH: htpasswd
#      REGISTRY_AUTH_HTPASSWD_PATH: /var/lib/registry/conf.d/htpasswd
#      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Flhar"
    volumes:
      - registry:/var/lib/registry
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.backend=registry"
        - "traefik.frontend.rule=Host:registry.flhar.ovh"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.port=5000"

  registry-web:
    image: konradkleine/docker-registry-frontend:v2
    networks:
      - registry
    environment:
      ENV_DOCKER_REGISTRY_HOST: registry
      ENV_DOCKER_REGISTRY_PORT: 5000
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.backend=registry-web"
        - "traefik.frontend.rule=Host:registry-web.flhar.ovh"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.port=80"
