apiVersion: v1
metadata:
  name: kube-lego
  namespace: kube-system
data:
  # modify this to specify your address
  lego.email: "flav.hardy@gmail.com"
  # configure letsencrypt's production api
  lego.url: "https://acme-v01.api.letsencrypt.org/directory"
kind: ConfigMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-apiserver-cm
  namespace: kube-system
data:
  8443: "kube-system/kube-apiserver-svc:443"
