# ConfigMap for config files
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
  client.cnf: |
              [client]
              port            = 3306
              protocol        = tcp
              user            = root
  mysqld.cnf: |
              # Template my.cnf for PXC
              # Edit to your requirements.
              [mysqld]
              bind-address = 0.0.0.0
              skip-host-cache
              skip-name-resolve
              server-id=1
              datadir=/var/lib/mysql
              socket=/var/run/mysqld/mysqld.sock
              #log-error=/var/log/mysqld.log
              pid-file=/var/run/mysqld/mysqld.pid
              #log-bin
              #log_slave_updates
              expire_logs_days=7
              # Disabling symbolic-links is recommended to prevent assorted security risks
              symbolic-links=0
              innodb_locks_unsafe_for_binlog = 1
              innodb_autoinc_lock_mode = 2
              default_storage_engine = InnoDB
              innodb_file_per_table
              max_connections = {{ .Values.max_connections }}
  mysqld_safe.cnf: |
                   #
                   # The Percona XtraDB Cluster 5.7 configuration file.
                   #
                   # One can use all long options that the program supports.
                   # Run program with --help to get a list of available options and with
                   # --print-defaults to see which it would actually understand and use.
                   #
                   # For explanations see
                   # http://dev.mysql.com/doc/mysql/en/server-system-variables.html
                   [mysqld_safe]
                   pid-file = /var/run/mysqld/mysqld.pid
                   socket   = /var/run/mysqld/mysqld.sock
                   nice     = 0
  wsrep.cnf: |
             [mysqld]
             # Path to Galera library
             wsrep_provider=/usr/lib/galera3/libgalera_smm.so
             # Cluster connection URL contains IPs of nodes
             #If no IP is found, this implies that a new cluster needs to be created,
             #in order to do that you need to bootstrap this node
             wsrep_cluster_address = gcomm://{{ .Chart.Name }}-0.{{ .Chart.Name }}-svc,{{ .Chart.Name }}-1.{{ .Chart.Name }}-svc,{{ .Chart.Name }}-2.{{ .Chart.Name }}-svc
             # In order for Galera to work correctly binlog format should be ROW
             binlog_format=ROW
             # MyISAM storage engine has only experimental support
             default_storage_engine=InnoDB
             # Slave thread to use
             wsrep_slave_threads= {{ .Values.wsrep_slave_threads }}
             wsrep_log_conflicts
             # This changes how InnoDB autoincrement locks are managed and is a requirement for Galera
             innodb_autoinc_lock_mode=2
             # Node IP address
             #wsrep_node_address=192.168.70.63
             # Cluster name
             wsrep_cluster_name= {{ .Values.wsrep_cluster_name }}
             #If wsrep_node_name is not specified,  then system hostname will be used
             #wsrep_node_name=pxc-cluster-node-1
             #pxc_strict_mode allowed values: DISABLED,PERMISSIVE,ENFORCING,MASTER
             pxc_strict_mode=ENFORCING
             # SST method
             wsrep_sst_method=xtrabackup-v2
             #Authentication for SST method
             wsrep_retry_autocommit = 4
