apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.mysqlRootPassword }}
  mysql-root-password:  {{ .Values.mysqlRootPassword | b64enc | quote }}
  {{ else }}
  mysql-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.sstPassword }}
  sst-password:  {{ .Values.sstPassword | b64enc | quote }}
  {{ else }}
  sst-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.sstUser }}
  sst-user:  {{ .Values.sstUser | b64enc | quote }}
  {{ else }}
  sst-user: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
