apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
  - name: {{ .Chart.Name }}
    port: 3306
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}
