################################################################
# Global configuration
################################################################
logLevel = "DEBUG"


defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "flav.hardy@gmail.com"
entryPoint = "https"

# File used for certificates storage.
# # WARNING, if you use Traefik in Docker, you have 2 options:
# #  - create a file on your host and mount it has a volume
# #      storageFile = "acme.json"
# #      $ docker run -v "/my/host/acme.json:acme.json" traefik
# #  - mount the folder containing the file has a volume
# #      storageFile = "/etc/traefik/acme/acme.json"
# #      $ docker run -v "/my/host/acme:/etc/traefik/acme" traefik
# #
storageFile = "acme.json" # mount it in a volume ;)

[[acme.domains]]
  main = "flavien-hardy.me"
  sans = ["api.flavien-hardy.me", "cloud.flavien-hardy.me", "registry.flavien-hardy.me"]
# Uncomment to load SSL cert on demand (be careful)
#onDemand = true
# Uncomment the line to run on the staging let's encrypt server
# Leave comment to go to prod
#caServer = "https://acme-staging.api.letsencrypt.org/directory"
################################################################
## Docker configuration backend
#################################################################

# Enable Docker configuration backend
#
# Optional
#
[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
#
# Required
#
endpoint = "unix:///var/run/docker.sock"

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a container.
#
# Required
#
domain = "flavien-hardy.me"

# Enable watch docker changes
#
# Optional
#
watch = true

##################################################################
# Web UI
###################################################################
[web]
address = ":8080"


[file]
watch = true
##################################################################
# Backends
###################################################################

[backends]
  [backends.dedi-os]
    [backends.dedi-os.servers.horizon]
        url = "http://10.0.0.146:80"
        weight = 1
##################################################################
# Frontends
###################################################################
#
[frontends]
  [frontends.dedi-os]
    backend = "dedi-os"
    passHostHeader = true
    [frontends.dedi-os.routes.horizon]
      rule = "Host:cloud.flavien-hardy.me"
