apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD_FILE
          value: /run/secrets/mysql_root_password
        image: mysql
        name: mysql
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: etherpad-data
      restartPolicy: Always
      volumes:
      - name: etherpad-data
        persistentVolumeClaim:
          claimName: etherpad-data
status: {}
