---
version: '3.1'

networks:
  hastebin:
    external: true

volumes:
  hastebin_data:
    driver: nfs
    driver_opts:
      share: "10.20.30.2:/hastebin_data"

services:
  hastebin:
    image: ogarcia/haste-server
    networks:
      - hastebin
    volumes:
      - hastebin_data:/srv/haste/data
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.backend=haste"
        - "traefik.frontend.rule=Host:hastebin.fhardy.fr"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.port=7777"
