# glusterfs
glusterfs_interface_fact: ansible_brcluster
glusterfs_default_brick: "/srv/brick"
glusterfs_volumes:
  - "{{ glusterfs_default_brick }}/init"
#  - "{{ glusterfs_default_brick }}/traefik_conf"
#  - "{{ glusterfs_default_brick }}/etherpad_data"
#  - "{{ glusterfs_default_brick }}/share"
#  - "{{ glusterfs_default_brick }}/registry"
#  - "{{ glusterfs_default_brick }}/jenkins"
#  - "{{ glusterfs_default_brick }}/hastebin_data"
#  - "{{ glusterfs_default_brick }}/ca"

# users
deploy_user_name: "pollux"
deploy_user_home: "/etc/{{ deploy_user_name }}"

# config
conf_directories:
  - traefik-conf
  - asciinema-conf

# cacert
ca_node: "dedi"
ca_name: dedi
cert_orga: "FH"
cert_country: "FR"

# consul
consul_version: "0.8.4"
consul_ca_file: "/etc/ssl/certs/dedi.crt"
consul_cert_file: "/etc/ssl/certs/{{ ansible_fqdn }}.crt"
consul_key_file: "/etc/ssl/private/{{ ansible_fqdn }}.key"
