apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver-svc
  namespace: kube-system
spec:
  type: ClusterIP
  selector:
    k8s-app: kube-apiserver
  ports:
    - protocol: TCP
      port: 443
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-apiserver-lb
  labels:
    name: kube-apiserver-lb
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: kube-apiserver-lb
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - image: quay.io/jcmoraisjr/haproxy-ingress
        name: haproxy-tcp-controller
        ports:
        - containerPort: 8443
          hostPort: 8443
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args:
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        - --tcp-services-configmap=$(POD_NAMESPACE)/kube-apiserver-cm
