#!/usr/bin/env ansible-playbook

- hosts: cluster
  tasks:
    - include_vars: conf/plain-vars.yml
    - include_vars: conf/encrypt-vars.yml
  tags:
    - always

- hosts: cluster
  become: true
  roles:
    - role: privatenetwork
      privatenetwork_network: "10.20.30.0/24"
      privatenetwork_vxlanprefix: "vx-c"
      privatenetwork_ipsec: true
      privatenetwork_ipsec_psk: true
