#!/usr/bin/env ansible-playbook

- hosts: cluster
  tasks:
    - name: Add mirrors
      copy:
        src: conf/xenial-mirrors
        dest: /etc/apt/sources.list
        owner: root
        group: root
        mode: 0644
    - name: Update cache
      apt:
        name:
        update_cache: true
